---
- name: Running Ansible Playboook
  hosts: ec2-54-227-75-103.compute-1.amazonaws.com
  tasks:
    - name: Deploying Kubernetes
      command: kubectl apply -f flaskapp_deployment.yaml
      become: yes
